<?php

defined("APPLICATION_TITLE") || define("APPLICATION_TITLE", "Chat App");

defined("FORM_MRTHOD_GET") || define("FORM_METHOD_GET", "GET");
defined("FORM_METHOD_POST") || define("FORM_METHOD_POST", "POST");

defined("REQUEST_PROCESSED") || define("REQUEST_PROCESSED", 1);
defined("REQUEST_GOT_ERROR") || define("REQUEST_GOT_ERROR", 0);

defined("ACCOUNT_STATUS_ACTIVE") || define("ACCOUNT_STATUS_ACTIVE", 1);
defined("ACCOUNT_STATUS_INACTIVE") || define("ACCOUNT_STATUS_INACTIVE", 2);

defined("FRIEND_REQUEST_STATUS_PENDING") || define("FRIEND_REQUEST_STATUS_PENDING", "pending");
defined("FRIEND_REQUEST_STATUS_ACCEPTED") || define("FRIEND_REQUEST_STATUS_ACCEPTED", "accepted");
defined("FREIND_REQUEST_STATUS_DECLINED") || define("FRIEND_REQUEST_STATUS_DECLINED", "declined");
defined("FRIEND_REQUEST_STATUS_BLOCKED") || define("FRIEND_REQUEST_STATUS_BLOCKED", 'blocked');

defined("LIMITED_POST_IN_RIGHTBAR") || define("LIMITED_POST_IN_RIGHTBAR", 10);

defined("NEW_JOINING_USER_POST") || define("NEW_JOINING_USER_POST", 1);
defined("PROFILE_INFO_UPDATED_POST") || define("PROFILE_INFO_UPDATED_POST", 1);
defined("POST_VISIBILITY_PUBLIC") || define("POST_VISIBILITY_PUBLIC","public");

defined("MEDIA_TYPE_IMAGE") || define("MEDIA_TYPE_IMAGE", "image");
defined("MEDIA_TYPE_VIDEO") || define("MEDIA_TYPE_VIDEO", "video");

defined("POSTING_TYPE_POST") || define("POSTING_TYPE_POST", 1);
defined("POSTING_TYPE_ADVERT") || define("POSTING_TYPE_ADVERT", 2);
defined("POSTING_TYPE_JOB_LISTING") || define("POSTING_TYPE_JOB_LISTING", 3);

defined("JOB_TYPE_FREELANCE") || define("JOB_TYPE_FREELANCE", 1);
defined("JOB_TYPE_FULL_TIME") || define("JOB_TYPE_FULL_TIME", 2);
defined("JOB_TYPE_INTERNSHIP") || define("JOB_TYPE_INTERNSHIP", 3);
defined("JOB_TYPE_PART_TIME") || define("JOB_TYPE_PART_TIME", 4);
defined("JOB_TYPE_TEMPORARY") || define("JOB_TYPE_TEMPORARY", 5);

defined("JOB_SUBMITTION_DRAFT") || define("JOB_SUBMITTION_DRAFT", 1);
defined("JOB_SUBMITTION_POSTING") || define("JOB_SUBMITTION_POSTING", 2);

defined("PUBLISHING_STATUS_DRAFT") || define("PUBLISHING_STATUS_DRAFT", 1);
defined("PUBLISHING_STATUS_PUBLIC") || define("PUBLISHING_STATUS_PUBLIC", 2);

defined("USER_TYPE_ADMIN") || define("USER_TYPE_ADMIN", "admin");
defined("USER_TYPE_USER") || define("USER_TYPE_USER", "user");

defined("COMMENT_TYPE_TEXT") || define("COMMENT_TYPE_TEXT", "text");
