<?php

defined("APPLICATION_TITLE") || define("APPLICATION_TITLE", "Chat App");

defined("FORM_MRTHOD_GET") || define("FORM_METHOD_GET", "GET");
defined("FORM_METHOD_POST") || define("FORM_METHOD_POST", "POST");

defined("REQUEST_PROCESSED") || define("REQUEST_PROCESSED", 1);
defined("REQUEST_GOT_ERROR") || define("REQUEST_GOT_ERROR", 0);

defined("FRIEND_REQUEST_STATUS_PENDING") || define("FRIEND_REQUEST_STATUS_PENDING", "pending");
defined("FRIEND_REQUEST_STATUS_ACCEPTED") || define("FRIEND_REQUEST_STATUS_ACCEPTED", "accepted");
defined("FREIND_REQUEST_STATUS_DECLINED") || define("FRIEND_REQUEST_STATUS_DECLINED", "declined");
defined("FRIEND_REQUEST_STATUS_BLOCKED") || define("FRIEND_REQUEST_STATUS_BLOCKED", 'blocked');

defined("LIMITED_POST_IN_RIGHTBAR") || define("LIMITED_POST_IN_RIGHTBAR", 10);

defined("NEW_JOINING_USER_POST") || define("NEW_JOINING_USER_POST", 1);
defined("POST_VISIBILITY_PUBLIC") || define("POST_VISIBILITY_PUBLIC","public");
